classdef LegacyMotorPage < scanimage.guis.configuration.ConfigurationPage
    properties
        hDimensionTable;
    end
    
    properties (SetObservable)
        invertDim = '';
        positionDeviceUnits = [];
        
        controllerType = '';
        
        mtrChoices = {};
        comChoices = {};
        comPort = '';
        
        customArgs;
        velocitySlow;
        velocityFast;
        moveCompleteDelay;
    end
    
    properties (Constant)
        modelClass = 'scanimage.components.motors.legacy.LegacyMotor';
    end
    
    methods
        function obj = LegacyMotorPage(hConfigEditor, mdfHeading, create)
            if nargin < 3 || isempty(create)
                create = false;
            end
            
            obj = obj@scanimage.guis.configuration.ConfigurationPage(hConfigEditor,create);
            
            obj.listLabel = mdfHeading;
            obj.heading = mdfHeading;
            obj.descriptionText = 'Configure legacy motor controller.';
            
            ph = 770;
            pw = 990;
            obj.hPanel = uipanel('parent',[],'BorderType','none','units','pixels','position',[0 0 pw ph]);
            
            uicontrol( ...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Configure connection settings for the selected motor stage controller.', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 ph-54 676 16]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Controller Type', ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-94 108 14]);
        
            most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'popupmenu', ...
                'String', {'None'}, ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'mtrChoices' 'choices'} {obj 'controllerType' 'choice'}},...
                'Position', [206 ph-98 150 22]);
                
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Serial COM Port', ...
                'TooltipString', 'If using serial communication, enter COM Port for the controller.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-134 108 14]);
            
            most.gui.popupMenuEdit(...
                'parent', obj.hPanel, ...
                'Position', [206 ph-138 60 22],...
                'validationFunc',@obj.validateComChoice,...
                'Bindings',{{obj 'comPort' 'string'} {obj 'comChoices' 'choices'}});
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Additional Params (Optional)', ...
                'TooltipString', 'Some motor controllers take optional parameters. Specify these as property-value pairs.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-174 148 14]);
        
            most.gui.paramCellArrayEdit(...
                'parent', obj.hPanel, ...
                'TooltipString', 'Some motor controllers take optional parameters. Specify these as property-value pairs.', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'ParameterOptions',{'baudRate' 'stageType' 'usbName'},...
                'Bindings',{{obj 'customArgs'}},...
                'Position', [206 ph-178 150 22]);
            
            
            uicontrol( ...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Customize dimension parameters by selecting how physical motor dimensions are mapped to the ScanImage XYZ coordinate system. You can also invert motor dimensions and customize the position unit conversion.', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 ph-240 676 32]);
            

            x = '<html><table border=0 width=75><TR><TD><center>1</center></TD></TR></table></html>';
            y = '<html><table border=0 width=75><TR><TD><center>2</center></TD></TR></table></html>';
            z = '<html><table border=0 width=75><TR><TD><center>3</center></TD></TR></table></html>';
            obj.hDimensionTable = uitable('parent', obj.hPanel, ...
                'ColumnName', {'Physical|Axis' 'Invert' 'Conversion|(um/unit)'}, ...
                'Data',{x false []; y false []; z false [];},...
                'ColumnFormat', {'numeric', 'logical', 'numeric'}, ...
                'ColumnEditable', [false, true true], ...
                'ColumnWidth', {75, 45 75}, ...
                'RowName', [],...
                'CellEditCallback',@obj.tblCb,...
                'Units', 'pixels', ...
                'Position', [46 ph-340 272 94]);
            
            
            uicontrol( ...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'For motors that support different move velocities, you can specify what velocity to use for short and long moves. The distance threshold for short and long moves can be specified later. (Optional)', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 ph-410 676 32]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Short Move Velocity', ...
                'TooltipString', 'Velocity to use for short moves. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-440 120 14]);
            
            most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'edit', ...
                'String', '', ...
                'TooltipString', 'Enter the velocity to use for moves smaller than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'velocitySlow' 'value'}},...
                'Position', [166 ph-445 60 22]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Long Move Velocity', ...
                'TooltipString', 'Enter the velocity to use for moves larger than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [286 ph-440 120 14]);
        
            most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'edit', ...
                'String', '', ...
                'TooltipString', 'Enter the velocity to use for moves larger than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'center', ...
                'Bindings',{{obj 'velocityFast' 'value'}},...
                'Units', 'pixels', ...
                'Position', [406 ph-445 60 22]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Some motors report that a move has completed before the stage has settled. This can cause error in the reading of the position. This option adds delay from when the move has completed to when the position is read.', ...
                'HorizontalAlignment', 'left', ...
                'fontsize',10,...
                'Units', 'pixels', ...
                'Position', [46 ph-505 676 32]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Move Complete Delay (sec)', ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-535 150 14]);
            
            most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'edit', ...
                'String', '0', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'moveCompleteDelay' 'value'}},...
                'Position', [206 ph-540 50 22]);
            
            obj.reload();
        end
        
        function delete(obj)
        end
        
        function reload(obj)
            obj.mtrChoices = [{' '} obj.hConfigEditor.motorName2RegMap.keys];
            obj.comChoices = [{'None'}; obj.hConfigEditor.availableComPorts];
            
            mdfData = obj.getCurrentMdfDataStruct();
            
            cInfo = obj.hConfigEditor.hMotorRegistry.getControllerInfo(mdfData.controllerType);
            if isempty(cInfo)
                obj.controllerType = ' ';
            else
                obj.controllerType = cInfo.ListName;
            end
            
            comP = mdfData.comPort;
            if isempty(comP)
                obj.comPort = 'None';
            elseif isnumeric(comP)
                obj.comPort = sprintf('COM%d',comP);
            else
                obj.comPort = comP;
            end
            
            obj.customArgs          = mdfData.customArgs;
            obj.invertDim           = mdfData.invertDim;
            obj.positionDeviceUnits = mdfData.positionDeviceUnits;
            obj.velocitySlow        = mdfData.velocitySlow;
            obj.velocityFast        = mdfData.velocityFast;
            obj.moveCompleteDelay   = mdfData.moveCompleteDelay;
            
            obj.refreshUI();
        end
        
        function s = getNewVarStruct(obj)
            if isempty(obj.controllerType) || strcmpi(obj.controllerType,' ')
                s.controllerType = '';
            else
                s.controllerType = obj.hConfigEditor.motorName2RegMap(obj.controllerType);
            end
                 
            if strcmp(obj.comPort,'None')
                s.comPort = [];
            elseif strncmpi(obj.comPort,'com',3) && (length(obj.comPort) > 3) && all(isstrprop(obj.comPort(4:end), 'digit'))
                s.comPort = str2double(obj.comPort(4:end));
            else
                s.comPort = obj.comPort;
            end
            
            s.customArgs          = obj.customArgs;
            s.invertDim           = obj.invertDim;
            s.positionDeviceUnits = obj.positionDeviceUnits;
            s.velocitySlow        = obj.velocitySlow;
            s.velocityFast        = obj.velocityFast;
            s.moveCompleteDelay   = obj.moveCompleteDelay;
        end
    end
    
    methods
        function refreshUI(obj,varargin)
            newDat = {false []; false []; false [];};
            
            N = min(3,numel(obj.invertDim));
            newDat(1:N,1) = arrayfun(@(x){x=='-'},obj.invertDim(1:N))';
            
            N = min(3,numel(obj.positionDeviceUnits));
            newDat(1:N,2) = num2cell(obj.positionDeviceUnits(1:N))';
            
            obj.hDimensionTable.Data(:,2:end) = newDat;
        end
        
        function [lvl,v,errMsg] = validateComChoice(obj,v,~)
            errMsg = '';
            if all(isstrprop(v, 'digit'))
                v = ['COM' v];
            elseif strncmpi(v,'com',3) && (length(v) > 3) && all(isstrprop(v(4:end), 'digit'))
                v(1:3) = 'COM';
            else
                if strcmp(v,'None')
                    lvl = 0;
                else
                    lvl = 2;
                    errMsg = 'Must be a numeric COM port ID.';
                end
                return;
            end
            
            if ismember(v,obj.comChoices)
                lvl = 0;
            else
                lvl = 1;
                errMsg = 'COM port not found. If ScanImage is running, this could be because the port is currently open.';
            end
        end
        
        function tblCb(obj,src,~)
            obj.invertDim = '+++';
            obj.invertDim([src.Data{:,2}]) = '-';
            
            un = src.Data(:,3);
            un(cellfun(@isempty,un)) = {nan};
            un = [un{:}];
            if all(isnan(un))
                obj.positionDeviceUnits = [];
                src.Data(:,3) = {[]};
            else
                obj.positionDeviceUnits = un;
                src.Data(:,3) = num2cell(un)';
            end
        end
    end
    
    %% Prop access
    methods        
        function set.controllerType(obj,v)            
            obj.controllerType = v;
        end
        
        function set.comPort(obj,v)
            obj.comPort = v;
        end
        
        function set.customArgs(obj,v)
            obj.customArgs = v;
        end
        
        function set.velocitySlow(obj,v)
            v(isnan(v)) = [];
            obj.velocitySlow = v;
        end
        
        function set.velocityFast(obj,v)
            v(isnan(v)) = [];
            obj.velocityFast = v;
        end
        
        function set.moveCompleteDelay(obj,v)
            if isempty(v)
                v = 0;
            end
            
            v(isnan(v)) = 0;
            obj.moveCompleteDelay = v;
        end
    end
end


%--------------------------------------------------------------------------%
% LegacyMotorPage.m                                                        %
% Copyright © 2020 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage is licensed under the Apache License, Version 2.0              %
% (the "License"); you may not use any files contained within the          %
% ScanImage release  except in compliance with the License.                %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
