function aboutDialog()            
    p = most.gui.centeredScreenPos([80, 34],'characters');

    obj.hFig = figure(...
        'Units','characters',...
        'Color',most.constants.Colors.vidrioBlue,...
        'MenuBar','none',...
        'Name',scanimage.SI.version(),...
        'NumberTitle','off',...
        'Position',p,...
        'Resize','off',...
        'Visible','off');

    logoPanel = uipanel(...
        'Parent',obj.hFig,...
        'Units','characters',...
        'Clipping','on',...
        'BorderType','none',...
        'Position',[0 25 80 9],...
        'Tag','logopanel');

    hLogo = scanimage.util.ScanImageLogo(logoPanel,false);

    infoPanel = uipanel(...
        'Parent',obj.hFig,...
        'Units','characters',...
        'Clipping','on',...
        'BorderType','none',...
        'Position',[0 0 80 25],...
        'Tag','infopanel');

    hLM = scanimage.util.private.LM();
    hLM.showInfo(infoPanel);

    set(obj.hFig,'Visible','on');
    
    hLogo.animate();
end



%--------------------------------------------------------------------------%
% aboutDialog.m                                                            %
% Copyright © 2020 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage is licensed under the Apache License, Version 2.0              %
% (the "License"); you may not use any files contained within the          %
% ScanImage release  except in compliance with the License.                %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
